// <auto-generated />
using System;
using System.Collections.Generic;
using DAL.DBcontext;
using DAL.ValueObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220707161849_dbbear")]
    partial class dbbear
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<ICollection<ImageValueObject>>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Options", b =>
                {
                    b.Property<Guid>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOptionEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OptionID");

                    b.ToTable("options", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.OptionValues", b =>
                {
                    b.Property<Guid>("ValuesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOptionValueEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OptionID")
                        .HasColumnType("uuid");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ValuesID");

                    b.HasIndex("OptionID");

                    b.ToTable("optionValues", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountPay")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsOrderEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PayingCustomer")
                        .HasColumnType("bigint");

                    b.Property<long>("Payments")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.OrderDetails", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOrderDetailEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.HasKey("OrderID", "VariantID");

                    b.HasIndex("VariantID");

                    b.ToTable("OrdertDetails", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.ProductOptions", b =>
                {
                    b.Property<Guid>("OptionID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProductOptionEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("OptionID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("productOptions");
                });

            modelBuilder.Entity("DAL.Entities.Products", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProductEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductID");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.ProductVariants", b =>
                {
                    b.Property<Guid>("VariantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<ICollection<ImageValueObject>>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ImportPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsProductVariantEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SkuID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VariantID");

                    b.HasIndex("ProductID");

                    b.ToTable("productVariants", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.RolesUser", b =>
                {
                    b.Property<Guid>("RolesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRolesUserEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RolesName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RolesID");

                    b.ToTable("rolesUsers", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.user", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<ImageValueObject>("Avatar")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsUserEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<ProfilesUser>>("Profile")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RolesID")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("RolesID");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.VariantValues", b =>
                {
                    b.Property<Guid>("ProductID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptionID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ValuesID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVariantValueEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("ProductID", "VariantID", "OptionID", "ValuesID");

                    b.HasIndex("ValuesID");

                    b.HasIndex("VariantID");

                    b.ToTable("variantValues", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.OptionValues", b =>
                {
                    b.HasOne("DAL.Entities.Options", "Options")
                        .WithMany("OptionValues")
                        .HasForeignKey("OptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Options");
                });

            modelBuilder.Entity("DAL.Entities.Order", b =>
                {
                    b.HasOne("DAL.Entities.user", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.OrderDetails", b =>
                {
                    b.HasOne("DAL.Entities.Order", "Orderds")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.ProductVariants", "ProductVariants")
                        .WithMany("OrderDetails")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orderds");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("DAL.Entities.ProductOptions", b =>
                {
                    b.HasOne("DAL.Entities.Options", "Options")
                        .WithMany("ProductOptions")
                        .HasForeignKey("OptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Products", "Products")
                        .WithMany("ProductOptions")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Options");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DAL.Entities.ProductVariants", b =>
                {
                    b.HasOne("DAL.Entities.Products", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DAL.Entities.user", b =>
                {
                    b.HasOne("DAL.Entities.RolesUser", "RolesUsers")
                        .WithMany("Users")
                        .HasForeignKey("RolesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolesUsers");
                });

            modelBuilder.Entity("DAL.Entities.VariantValues", b =>
                {
                    b.HasOne("DAL.Entities.OptionValues", "OptionValue")
                        .WithMany("VariantValues")
                        .HasForeignKey("ValuesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.ProductVariants", "ProductVariant")
                        .WithMany("VariantValues")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionValue");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("DAL.Entities.Options", b =>
                {
                    b.Navigation("OptionValues");

                    b.Navigation("ProductOptions");
                });

            modelBuilder.Entity("DAL.Entities.OptionValues", b =>
                {
                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DAL.Entities.Products", b =>
                {
                    b.Navigation("ProductOptions");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("DAL.Entities.ProductVariants", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("DAL.Entities.RolesUser", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Entities.user", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
